#!/usr/bin/env bash
# unifi-setup: Interactive setup wizard for unifi-nix
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Source common library if available
if [[ -f "$SCRIPT_DIR/lib/common.sh" ]]; then
  # shellcheck source=lib/common.sh
  source "$SCRIPT_DIR/lib/common.sh"
else
  # Fallback colors
  COLOR_RED='\033[0;31m'
  COLOR_GREEN='\033[0;32m'
  COLOR_YELLOW='\033[0;33m'
  COLOR_BLUE='\033[0;34m'
  COLOR_CYAN='\033[0;36m'
  COLOR_RESET='\033[0m'
  COLOR_BOLD='\033[1m'

  log_info() { echo -e "${COLOR_BLUE}[INFO]${COLOR_RESET} $*"; }
  log_success() { echo -e "${COLOR_GREEN}[OK]${COLOR_RESET} $*"; }
  log_warn() { echo -e "${COLOR_YELLOW}[WARN]${COLOR_RESET} $*" >&2; }
  log_error() { echo -e "${COLOR_RED}[ERROR]${COLOR_RESET} $*" >&2; }
  log_step() { echo -e "${COLOR_CYAN}==>${COLOR_RESET} ${COLOR_BOLD}$*${COLOR_RESET}"; }
fi

# =============================================================================
# Setup Wizard
# =============================================================================

echo ""
echo -e "${COLOR_BOLD}╔══════════════════════════════════════════════════════════════╗${COLOR_RESET}"
echo -e "${COLOR_BOLD}║              unifi-nix Setup Wizard                          ║${COLOR_RESET}"
echo -e "${COLOR_BOLD}╚══════════════════════════════════════════════════════════════╝${COLOR_RESET}"
echo ""

# Step 1: Get UDM IP
log_step "Step 1: UDM Connection"
echo ""
echo "Enter your UniFi Dream Machine IP address or hostname."
echo "This is typically 192.168.1.1 for default setups."
echo ""
read -rp "UDM IP address: " UDM_HOST

if [[ -z $UDM_HOST ]]; then
  log_error "UDM IP address is required"
  exit 1
fi

# Step 2: Test SSH connectivity
log_step "Step 2: Testing SSH Connection"
echo ""
echo "Testing SSH connection to root@$UDM_HOST..."
echo ""

SSH_USER="root"
if ssh -o ConnectTimeout=5 -o BatchMode=yes "$SSH_USER@$UDM_HOST" "echo ok" &>/dev/null; then
  log_success "SSH connection successful"
else
  log_warn "SSH connection failed"
  echo ""
  echo "Please ensure:"
  echo "  1. SSH is enabled on your UDM (Settings > System > SSH)"
  echo "  2. Your SSH key is authorized on the UDM"
  echo ""
  echo "To add your SSH key:"
  echo "  ssh-copy-id root@$UDM_HOST"
  echo ""
  read -rp "Press Enter after setting up SSH, or Ctrl+C to abort..."

  # Test again
  if ssh -o ConnectTimeout=5 -o BatchMode=yes "$SSH_USER@$UDM_HOST" "echo ok" &>/dev/null; then
    log_success "SSH connection successful"
  else
    log_error "SSH connection still failing. Please check your setup."
    exit 1
  fi
fi

# Step 3: Test MongoDB connectivity
log_step "Step 3: Testing MongoDB Connection"
echo ""

if ssh -o ConnectTimeout=5 "$SSH_USER@$UDM_HOST" "mongo --quiet --port 27117 ace --eval 'db.stats()'" &>/dev/null; then
  log_success "MongoDB connection successful"
else
  log_error "Cannot connect to MongoDB on port 27117"
  log_error "Ensure the UDM has fully booted"
  exit 1
fi

# Step 4: Get site name
log_step "Step 4: Site Configuration"
echo ""
echo "Enter a name for this site configuration."
echo "This will be used for the config file name."
echo ""
read -rp "Site name [home]: " SITE_NAME
SITE_NAME="${SITE_NAME:-home}"

# Sanitize site name
SITE_NAME=$(echo "$SITE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')

# Step 5: Create sites directory
log_step "Step 5: Creating Configuration"
echo ""

SITES_DIR="./sites"
mkdir -p "$SITES_DIR"

CONFIG_FILE="$SITES_DIR/${SITE_NAME}.nix"

# Step 6: Import existing config or create template
echo "Would you like to:"
echo "  1) Import existing configuration from UDM"
echo "  2) Start with a blank template"
echo ""
read -rp "Choice [1]: " IMPORT_CHOICE
IMPORT_CHOICE="${IMPORT_CHOICE:-1}"

if [[ $IMPORT_CHOICE == "1" ]]; then
  log_step "Importing existing configuration..."

  if [[ -f "$SCRIPT_DIR/import.sh" ]]; then
    "$SCRIPT_DIR/import.sh" "$UDM_HOST" "$CONFIG_FILE"
    log_success "Configuration imported to $CONFIG_FILE"
  else
    log_warn "Import script not found, creating template instead"
    IMPORT_CHOICE="2"
  fi
fi

if [[ $IMPORT_CHOICE == "2" ]]; then
  cat >"$CONFIG_FILE" <<EOF
# UniFi configuration for $SITE_NAME
# Generated by unifi-nix setup wizard
{
  unifi = {
    host = "$UDM_HOST";
    site = "default";

    networks = {
      # Main network (default VLAN)
      Default = {
        subnet = "192.168.1.1/24";
        purpose = "corporate";
        networkGroup = "LAN";
        dhcp = {
          enable = true;
          start = "192.168.1.100";
          end = "192.168.1.254";
          dns = [ "1.1.1.1" "8.8.8.8" ];
        };
      };

      # Example: IoT network on VLAN 10
      # IoT = {
      #   vlan = 10;
      #   subnet = "192.168.10.1/24";
      #   purpose = "corporate";
      #   networkGroup = "LAN";
      #   isolate = true;
      #   dhcp = {
      #     enable = true;
      #     start = "192.168.10.100";
      #     end = "192.168.10.254";
      #   };
      # };
    };

    wifi = {
      # Main WiFi
      main = {
        ssid = "MyNetwork";
        passphrase = { _secret = "wifi/main"; };
        network = "Default";
        security = "wpapsk";
        wpa3 = {
          enable = true;
          transition = true;
        };
        bands = [ "2g" "5g" ];
      };
    };

    # Port forwards
    portForwards = {
      # https = {
      #   srcPort = 443;
      #   dstIP = "192.168.1.100";
      #   protocol = "tcp";
      # };
    };

    # DHCP reservations
    dhcpReservations = {
      # server = {
      #   mac = "00:11:22:33:44:55";
      #   ip = "192.168.1.100";
      #   network = "Default";
      # };
    };

    # Firewall policies (zone-based, requires UniFi 10.x+)
    firewall.policies = {
      # block-iot-to-default = {
      #   action = "block";
      #   sourceZone = "internal";
      #   sourceType = "network";
      #   sourceNetworks = [ "IoT" ];
      #   destinationZone = "internal";
      #   destinationType = "network";
      #   destinationNetworks = [ "Default" ];
      # };
    };
  };
}
EOF
  log_success "Template created at $CONFIG_FILE"
fi

# Step 7: Set up secrets
log_step "Step 6: Secrets Configuration"
echo ""
echo "WiFi passwords are specified as secret references."
echo "You can set them via environment variables or files."
echo ""
echo "For the example config, set your WiFi password:"
echo ""
read -rsp "WiFi password (hidden): " WIFI_PASS
echo ""

if [[ -n $WIFI_PASS ]]; then
  SECRETS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/unifi-nix/secrets"
  mkdir -p "$SECRETS_DIR/wifi"
  echo -n "$WIFI_PASS" >"$SECRETS_DIR/wifi/main"
  chmod 600 "$SECRETS_DIR/wifi/main"
  log_success "Secret saved to $SECRETS_DIR/wifi/main"
  echo ""
  echo "Before deploying, export:"
  echo "  export UNIFI_SECRETS_DIR=$SECRETS_DIR"
fi

# Step 8: Summary
echo ""
log_step "Setup Complete!"
echo ""
echo "Your configuration is ready at: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo ""
echo "  1. Edit your configuration:"
echo "     \$EDITOR $CONFIG_FILE"
echo ""
echo "  2. Set secrets:"
echo "     export UNIFI_SECRETS_DIR=$SECRETS_DIR"
echo ""
echo "  3. Preview changes:"
echo "     nix run .#diff -- $CONFIG_FILE $UDM_HOST"
echo ""
echo "  4. Deploy:"
echo "     nix run .#deploy -- $CONFIG_FILE $UDM_HOST"
echo ""
echo "For more examples, see: examples/"
echo "For help, see: docs/troubleshooting.md"
echo ""
